### ISSUE TITLE
redisbloom for redis is trying to change the compatible port to something other than 6379 but it's not working?

### ISSUE THREAD

**Issue by ponponon** [RedisBloom/RedisBloom#766]
redisbloom for redis wants to change the compatible port to something other than 6379 but it doesn't work?

``docker-compose.yaml``
``yaml
version: ‘3’

services. 
  redis.
    container_name: rebloom2
    restart: always
    image: redislabs/rebloom:2.6.12
    ports: ‘6377:6377
      - ‘6377:6377’
    volumes.
      - . /volumes:/data # /usr/local/redis/data is the path to your host; /data is the path inside the container, where redis saves all data that needs to be persisted to the /data directory.
      - . /redis.conf:/etc/redis/redis.conf # redis.conf file is already prepared, you can put it in this path, or you can modify it yourself, for example, put it in the project path.

```

``conf
# The address of this file should correspond to the one to the left of the colon in /usr/local/redis/redis.conf:/etc/redis/redis.conf in your docker-compose.yaml.
# redis supports both persistence mechanisms: RDB & AOF.
# https://juejin.cn/post/6844903716290576392

appendonly yes
#default: persistent file
appendfilename ‘appendonly.aof’
#default: synchronise every second
appendfsync everysec

port 6377
# bind 0.0.0.0, or you may not be able to connect to the server without specifying the port.
bind 0.0.0.0


# maxmemory 100mb
# appendonly yes
# appendfilename ‘appendonly.aof’
# appendfsync everysec
```

After I change the default port to 6377, the client can't connect.

```shell
╭─pon@T4GPU ~
╰─➤ iredis -h 127.0.0.1 -p 6377
Error while reading from 127.0.0.1:6377 : (104, ‘Connection reset by peer’) retrying... retry left: 2
Error while reading from 127.0.0.1:6377 : (104, ‘Connection reset by peer’) retrying... retry left: 1
iredis 1.13.2 (Python 3.10.12)
redis-server Unknown (Error while reading from 127.0.0.1:6377 : (104, ‘Connection reset by peer’))
Home: https://iredis.io
Issues: https://iredis.io/issues
127.0.0.1:6377> exit
```

However, if you change the redis port to keep 6379 and just change the docker mapping port to `6377:6379`, the client will be able to connect successfully!

How do I change redis.conf to change the compatible ports if redisbloom is not the same as standard redis? Is it different from standard redis?

----

Standard redis can be changed to 6377.

```yaml
version: "3"

services: 
  redis:
    container_name: redis7-bookworm
    restart: always
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"
    volumes:
      - ./volumes:/data # /usr/local/redis/data 是你宿主机的路径；/data 是容器内的路径，容器内的 redis 会把需要持久化的数据都保存到 /data 目录下
      - ./redis.conf:/etc/redis/redis.conf # redis.conf 这个文件已经准备好了，可以放到这个路径，也可以自己修改，比如放到项目路径中
    command: redis-server /etc/redis/redis.conf
```

```conf
# 这个文件的地址，和你的 docker-compose.yaml 中的 /usr/local/redis/redis.conf:/etc/redis/redis.conf 冒号左边的要对应起来
# redis 支持两者持久化机制：RDB&AOF
# https://juejin.cn/post/6844903716290576392

appendonly yes
#default: 持久化文件
appendfilename "appendonly.aof"
#default: 每秒同步一次
appendfsync everysec

port 6379
# 绑定端口,不指定外网可能连不上服务器
bind 0.0.0.0
```
